### PR TITLE
Update uncontrollable package

### PR DESCRIPTION
**Pull request by yantakus**
to fix compatibility with react v16 (there is no react/lib/* and react-dom/lib/* anymore).

### CODE REVIEW

**Comment by yantakus** [comment]
@aruberto Could you please explain why `src` folder disappears when I install the package providing url of my fork instead of version number like this:
```
"react-foundation-components": "https://github.com/yantakus/react-foundation-components.git"
```

I wanted to make sure my fix actually helps, but I can't do it...

**Comment by yantakus** [comment]
This is tested properly now. The package now requires react >= 16 to work (updated devDependencies and peerDependencies). So you should add this info to changelog.

**Comment by yantakus** [comment]
Had to publish my fork to npm with a new name `react-foundation-components-fork`. I'll remove it when you merge this PR.

**Comment by aruberto** [comment]
image

Think the version of react-router that doc pages use doesn't work with React v16 so I can't verify that everything works. I'll trust that you have tested it and revisit later.

**Comment by yantakus** [comment]
@aruberto I can not test docs pages, because when I pun `npm run start-docs` I get the following error when I open `http://0.0.0.0:3000/` in chrome: `Cannot GET /`. Any ideas? Tried `start-examples-css-modules` and it works fine for me.

**Comment by antonioruberto-okta** [comment]
@yantakus Try http://0.0.0.0:3000/react-foundation-components

**Comment by yantakus** [comment]
@antonioruberto-okta thanks. I've fixed the docs, please have a look at #32.

**Comment by beautyfree** [comment]
The code in the constructor causes the server-side rendering error:
```
Rendering error:  ReferenceError: document is not defined
    at new OverlayTrigger (some-path/node_modules/react-foundation-components/lib/util/overlay-trigger/index.js:413:23)
```
[Line 413](https://github.com/aruberto/react-foundation-components/pull/31/files#diff-7f9c257e75a5f4d4a7f426b59382860eR151)

**Pull request merged**
